name = "Mac OS Optimized"
author = "scriptmunkee"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49b1b487628a45cd6163e8f5e953d69fbd354488b92aab35b11adbc95171da1b"

[versions]
fabric = "0.15.7"
minecraft = "1.20.4"
