name = "Mac OS Optimized"
author = "scriptmunkee"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "84732efc247f5e1ef4da6e203491cd19c05a4038b769cd84d17e25a0c50622c0"

[versions]
fabric = "0.15.11"
minecraft = "1.21"

[options]
