name = "Mac OS Optimized"
author = "scriptmunkee"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c0f2cf5e5f387dcd0e066fea2c3fa013c15ce3e7e312d7eef20b83cee509032"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"

[options]
acceptable-game-versions = []
