name = "Mac OS Optimized"
author = "scriptmunkee"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fdb0d4a949fff364b494a2e6be354f70e67d6a0f300c4611c2971d03a4dd5a3c"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"

[options]
acceptable-game-versions = []
