name = "Mac OS Optimized"
author = "scriptmunkee"
version = "1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a4bfbd8bc0acba902fecccf471634fe7593e34555c0987f337f63d5b50a2130"

[versions]
fabric = "0.19.3"
minecraft = "26.2"

[options]
acceptable-game-versions = []
