#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun May 17 01:16:59 EDT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=12
shaderPack=BSL_v10.1.3.zip
