#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun May 17 12:52:24 EDT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=12
shaderPack=Mellow Shader v3.1.1.zip
