name = "Mac OS Optimized"
author = "scriptmunkee"
version = "1.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c6240195aadd022baa18498ff4af0e77491f50b34b6cf0e8156cd47f826cebf7"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.3", "1.21.1"]
